version: "3.3"
services:
  api:
    container_name: "api-kuclap"
    build: "./api"
    ports:
      - "3000:3000"
    volumes:
      - "./api:/go/src/app"
    depends_on:
      - "mongo"
  mongo:
    container_name: "mongo-kuclap"
    image: "mongo:latest"
    ports:
      - "27100:27017"
