FROM golang:1.15

COPY . /go/src/github.com/KUclap/KUclap-review
WORKDIR /go/src/github.com/KUclap/KUclap-review

RUN go get ./...
RUN go build -o ./builder/kuclap-review-api .

ENV KIND=staging 
CMD ["./builder/kuclap-review-api"]

EXPOSE 8000