name: Deploy-to-DO-production

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Review API - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          DB_SERVER: ${{ secrets.ENV_DB_SERVER }}
          ORIGIN_ALLOWED: ${{ secrets.ENV_ORIGIN_ALLOWED }}
          PORT: ${{ secrets.ENV_PORT }}
        with:
          name: kuclap/kuclap-review/kuclap-review-api
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/API.Dockerfile
          tags: "1.0.0, latest"
          buildargs: DB_SERVER,ORIGIN_ALLOWED,PORT
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DO_GANDALF_HOST }}
          username: ${{ secrets.DO_GANDALF_USERNAME }}
          password: ${{ secrets.DO_GANDALF_PASSWORD }}
          port: ${{ secrets.DO_GANDALF_PORT }}
          envs: GIT_USERNAME, GITHUB_TOKEN
          script: |
            docker stop kuclap-review-api
            docker container prune -f 
            docker image prune -f
            docker login docker.pkg.github.com -u $GIT_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kuclap/kuclap-review/kuclap-review-api:latest
            docker run --name kuclap-review-api --network=kuclap --restart=always  -dit -p 8008:8000 docker.pkg.github.com/kuclap/kuclap-review/kuclap-review-api:latest
