name: Deploy-to-DO-pre-production

on:
    push:
        branches:
            - pre-prod-release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Review API - Publish to Github Packages Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              env:
                  GIT_ACCESS_TOKEN_CURL_CONFIG: ${{ secrets.GIT_ACCESS_TOKEN_CURL_CONFIG }}
                  ARG_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  ARG_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  ARG_AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
              with:
                  name: kuclap/kuclap-review/kuclap-pre-prod-review-api
                  registry: docker.pkg.github.com
                  username: ${{ secrets.GIT_USERNAME }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  dockerfile: ./docker/PreProd.Dockerfile
                  tags: '1.0.0, latest'
                  buildargs: GIT_ACCESS_TOKEN_CURL_CONFIG,ARG_AWS_ACCESS_KEY_ID,ARG_AWS_SECRET_ACCESS_KEY,ARG_AWS_DEFAULT_REGION
            - name: Deploy package to digitalocean
              uses: appleboy/ssh-action@master
              env:
                  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  host: ${{ secrets.DO_GANDALF_HOST }}
                  username: ${{ secrets.DO_GANDALF_USERNAME }}
                  password: ${{ secrets.DO_GANDALF_PASSWORD }}
                  port: ${{ secrets.DO_GANDALF_PORT }}
                  envs: GIT_USERNAME, GITHUB_TOKEN
                  script: |
                      docker stop kuclap-pre-prod-review-api
                      docker container prune -f 
                      docker image prune -f
                      docker login docker.pkg.github.com -u $GIT_USERNAME -p $GITHUB_TOKEN
                      docker pull docker.pkg.github.com/kuclap/kuclap-review/kuclap-pre-prod-review-api:latest
                      docker run --name kuclap-pre-prod-review-api --network=kuclap-pre-prod --restart=always  -dit -p 8089:8089 docker.pkg.github.com/kuclap/kuclap-review/kuclap-pre-prod-review-api:latest
