name: Deploy

on:
    push:
        branches:
            - stag-release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  usedocker: true
                  docker_build_args: |
                      GIT_ACCESS_TOKEN_CURL_CONFIG
                      AWS_ACCESS_KEY_ID
                      AWS_SECRET_ACCESS_KEY

              env:
                  GIT_ACCESS_TOKEN_CURL_CONFIG: ${{secrets.GIT_ACCESS_TOKEN_CURL_CONFIG}}
                  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
